//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDbFirstApproachRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestTab
    {
        public int RestId { get; set; }
        public string RestName { get; set; }
        public string CusineType { get; set; }
    }
}
